PREFIX wdrs: <http://www.w3.org/2007/05/powder-s#>
PREFIX ceo: <https://data.cultureelerfgoed.nl/vocab/def/ceo2#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX owms: <http://standaarden.overheid.nl/owms/terms/>
select ?s ?p ?o ?g where {
    graph ?g {
		?s ?p ?o .
        ?g rdf:type ceo:CultuurHistorischObjectbeschrijving .
    }

    # Geldigheidsbepaling
    ?g ceo:beginGeldigheid ?begindatum .
    filter (?begindatum <= now())
    filter not exists { ?g ceo:eindGeldigheid ?einddatum .}
    # Bronbepaling
    ?g prov:wasAttributedTo owms:Rijksdienst_voor_het_Cultureel_Erfgoed .
}
